<?php

function moodle_services_menu(){
  $items['admin/config/moodle_services']=array(
    'type'=>MENU_NORMAL_ITEM,
    'title'=>t("Moodle Services Settings"),
    'page callback'=>'drupal_get_form',
    'page arguments'=>array('moodle_services_admin_settings_form'),
    'access callback'=>'user_access',
    'access arguments'=>array('access content'),
    'file'=>'moodle_services.admin.inc'
  );
  return $items;
}


function moodle_services_rules_action_info() {

  $items['create_cohort'] = array(
    'label' => t('Create a Cohort'),
    'base' => 'moodle_services_create_cohort',
    'parameter' => array(
      'node' => array(
        'type' => 'node',
        'label' => t('Content'),
        'save' => TRUE
      ),
      'idnumber' => array(
        'type' => 'text',
        'label' => t('Source for the ID Number field'),
        'value'=>"node:nid",
        'restriction'=>'selector',
      ),
      'title' => array(
        'type' => 'text',
        'label' => t('Name Source'),
        'description' => t('The source of the cohort name.'),
        'restriction' => 'selector',
      ),
      'description' => array(
        'type' => 'text',
        'label' => t('Description'),
        'description' => t('The source of the cohort description field.'),
        'restriction' => 'selector',
      ),

    ),
    'category' => t('Moodle Services'),
  );
  $items['enrol_in_cohort'] = array(
    'label' => t('Enrol user in Cohort'),
    'base' => 'moodle_services_cohort_enrol',
    'parameter' => array(
      'node' => array(
        'type' => '*',
        'label' => t('Cohort Entity'),
        'description' => t('Entity correlating to cohort'),
        'save' => TRUE
      ),
      'user' => array(
        'type' => 'user',
        'label' => t('User'),
        'description' => t('User to add to cohort'),
        'save' => false,
      ),
    ),
    'category' => t('Moodle Services'),
  );
  $items['unenrol_in_cohort'] = array(
    'label' => t('Remove User from Cohort'),
    'base' => 'moodle_services_cohort_unenrol',
    'parameter' => array(
      'node' => array(
        'type' => '*',
        'label' => t('Cohort Entity'),
        'description' => t('Entity correlating to cohort'),
        'save' => false
      ),
      'user' => array(
        'type' => 'user',
        'label' => t('User'),
        'description' => t('User to add to cohort'),
        'save' => false,
      ),
    ),
    'category' => t('Moodle Services'),
  );
  return $items;
}

function moodle_services_create_cohort($node, $idnumber, $title, $description, $fieldselectors, RulesState $state, RulesAction $action, $command){
  module_load_include("inc", 'moodle_services', 'moodle_REST');

  $cohorts = new moodle_cohorts();
  $result=$cohorts->create($idnumber, $title, $description);
  $mapping=array(
    'entity'=>'node',
    'type'=>$node->type,
    'id'=>$node->nid,
    'vid'=>$node->vid,
    'moodle_object'=>"cohort",
    'object_id'=>$result[0]->id,
  );
}

function moodle_services_cohort_enrol($entity, $user, $fieldselectors, RulesState $state, RulesAction $action, $command){
  module_load_include("inc", 'moodle_services', 'moodle_REST');
  $cohorts = new moodle_cohorts();
  $cohorts->enrol($entity->nid, $user->uid);
}

function moodle_services_cohort_unenrol($entity, $user, $fieldselectors, RulesState $state, RulesAction $action, $command){
  module_load_include("inc", 'moodle_services', 'moodle_REST');
  $cohorts = new moodle_cohorts();
  $cohorts->unenrol($entity->nid, $user->uid);

}